### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by canewsin** [comment]
@rex4539 Thanks for the PR, please push this to https://github.com/ZeroNetX/ZeroNet/tree/py3-internal branch, Plugins are moved to separate repo.

**Comment by rex4539** [comment]
Please feel free to edit my commit and fix the conflicts because I'm not very good at git commands.

**Comment by canewsin** [comment]
@rex4539 no problem, I will take care of it.

**Comment by rex4539** [comment]
Looks like the Python implementation is dropped, so closing.

**Pull request closed without merging**
