### PR TITLE
Update README-ru.md

### PR DESCRIPTION
**Pull request by BratishkaErik**

### CODE REVIEW

**Comment by canewsin** [comment]
@BratishkaErik could you remove the patreon link on first line! Currently My Patreon A/c is not working

**Comment by BratishkaErik** [comment]
> @BratishkaErik could you remove the patreon link on first line! Currently My Patreon A/c is not working

Yes, but I guess I'm too late lol:)

**Comment by canewsin** [comment]
@BratishkaErik could you check ru translations on zeronet.dev are correct ?

**Comment by BratishkaErik** [comment]
> zeronet.dev

I can't change language to Russian (but I can cahnge to German etc.)

**Comment by canewsin** [comment]
Fixed Now, Now they are properly loading, you can check now.

**Comment by BratishkaErik** [comment]
Mmm, acceptable, where can I edit this page?

**Comment by canewsin** [comment]
here
https://github.com/ZeroNetX/zeronet.dev/blob/master/languages/ru.json
thanks for your contributions.

If you have time, you can help translating this, thanks for your contributions
https://zerolink.ml/list/ThreadIt.bit/translations/?file=translations/strings-en.json

**Comment by BratishkaErik** [comment]
> here https://github.com/ZeroNetX/zeronet.dev/blob/master/languages/ru.json thanks for your contributions.
> 
> If you have time, you can help translating this, thanks for your contributions https://zerolink.ml/list/ThreadIt.bit/translations/?file=translations/strings-en.json

OK, but I'm going to sleep, let's continue tomorrow.

**Comment by canewsin** [comment]
@BratishkaErik no problem, thanks you, good night man.

**Comment by caryoscelus** [comment]
@BratishkaErik this project is not ZeroNet (it's a fork) , please edit readme accordingly

**Comment by canewsin** [comment]
@caryoscelus thanks for reporting, ZeroNet names are still remained in ReadMe, will modify them.

**Pull request merged**
