### PR TITLE
Make notification's close button bigger in small screens

### LINKED ISSUE #105: Make the notification close button larger for mobile devices

### PR DESCRIPTION
**Pull request by zolagonano**
Fixes #105 

### **screenshots**

- Before:
screenshot before

- After: 
screenshot after

### CODE REVIEW

**Comment by canewsin** [comment]
@zolagonano Always push pr to py3-internal branch

**Comment by zolagonano** [comment]
> Always push pr to py3-internal branch

@canewsin  Done!

**Comment by canewsin** [comment]
@zolagonano to me, it's better make the close mark, size of notification banner or provide an extra button for mobile devices to close notification.

**Comment by zolagonano** [comment]
@canewsin Like this?
screenshot

**Comment by canewsin** [comment]
> @canewsin Like this? screenshot

Yes

**Comment by zolagonano** [comment]
@canewsin Done!

**Comment by canewsin** [comment]
@zolagonano Made some modifications, any suggessions ?

image

I think we can roll this to all screen sizes.

```css
.notification .close:hover { color: white }
.notification .close:active, .notification .close:focus { color: white }
.notification .close {
    margin: 10px; padding: 0px; display: block; width: 30px; height: 30px;
    text-align: center; background-color: tomato; line-height: 25px; vertical-align: bottom; font-size: 30px; color: white;
}
```

**Comment by zolagonano** [comment]
> @zolagonano Made some modifications, any suggessions ?
> 
> image
> 
> I think we can roll this to all screen sizes.
> 
> ```css
> .notification .close:hover { color: white }
> .notification .close:active, .notification .close:focus { color: white }
> .notification .close {
>     margin: 10px; padding: 0px; display: block; width: 30px; height: 30px;
>     text-align: center; background-color: tomato; line-height: 25px; vertical-align: bottom; font-size: 30px; color: white;
> }
> ```

Great, i'll implement it for all screen sizes :)

**Comment by canewsin** [comment]
@zolagonano Also note that there is slight alignment issue for active and inactive button, try to fix that.

> @zolagonano Made some modifications, any suggessions ?
> 
> image

**Comment by zolagonano** [comment]
@canewsin I have also added 20px to the width of notifications

**Comment by canewsin** [comment]
> @canewsin I have also added 20px to the width of notifications

Provide a visual change(screenshot) as before.

**Comment by zolagonano** [comment]
> Provide a visual change(screenshot) as before.

Also i have changed the margin-top in select class.
before:

screenshot before

after:
screenshot after

---

small screens:
screenshot smaller

bigger screens:
screenshot bigger

**Comment by styromaniac** [comment]
How are you targeting mobile devices? What media queries?

**Comment by zolagonano** [comment]
> How are you targeting mobile devices? What media queries?

@styromaniac First, I made that button bigger for screens smaller than 600px, but caneswin suggested implementing it for all screen sizes.
Now it's bigger in all screen sizes.

**Comment by styromaniac** [comment]
> > How are you targeting mobile devices? What media queries?
> 
> @styromaniac First, I made that button bigger for screens smaller than 600px, but caneswin suggested implementing it for all screen sizes. Now it's bigger in all screen sizes.

Okay. If it had to be for touch devices, for future reference, it's ```(pointer:coarse)```.

**Comment by zolagonano** [comment]
> > > How are you targeting mobile devices? What media queries?
> > 
> > 
> > @styromaniac First, I made that button bigger for screens smaller than 600px, but caneswin suggested implementing it for all screen sizes. Now it's bigger in all screen sizes.
> 
> Okay. If it had to be for touch devices, for future reference, it's `(pointer:coarse)`.

I didn't know that, thanks :)

**Pull request merged**
